---
deployment:
  tasks:
#    - export DEPLOYPATH=/home/zeme1231/public_html/tchooz
#    - export REPOPATH=
#    - /bin/cp * $DEPLOYPATH
#    - cd $DEPLOYPATH
#    - /usr/local/bin/composer install --no-dev
#    - /usr/local/bin/npm install
#    - /usr/local/bin/npm run build

    # NOTE: public_html on cPanel must not be removed or renamed.
    # This folder has owner USER:nobody, and the USER user does not have
    # access to change owner. So this folder must stay as-is to keep the nobody
    # group, which is critical to the site working. A new folder won't work.
    - export DEPLOYPATH=/home/zeme1231/public_html/tchooz
    - export REPOPATH=/home/zeme1231/repositories/tchooz
    # Remove previous old files, if any.
    - /bin/rm -Rf ${DEPLOYPATH}_old
    # Copy old site files to another directory.
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    # Sync repository files to the deploy target path, excluding .git folder.
    # --delete-after will remove deleted files and folders after syncing.
    - /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
    # Set correct permissions.
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
